(cl:in-package hust_fw_formation_control-msg)
(cl:export '(PITCH_ANGLE-VAL
          PITCH_ANGLE
          YAW_ANGLE-VAL
          YAW_ANGLE
          YAW_VALID-VAL
          YAW_VALID
          ROLL_ANGLE-VAL
          ROLL_ANGLE
          THRUST-VAL
          THRUST
          LATITUDE-VAL
          LATITUDE
          ALTITUDE-VAL
          ALTITUDE
          LONGITUDE-VAL
          LONGITUDE
          RELATIVE_ALT-VAL
          RELATIVE_ALT
          AIRSPEED-VAL
          AIRSPEED
          NED_VEL_X-VAL
          NED_VEL_X
          NED_VEL_Y-VAL
          NED_VEL_Y
          NED_VEL_Z-VAL
          NED_VEL_Z
          GLOBAL_VEL_X-VAL
          GLOBAL_VEL_X
          GLOBAL_VEL_Y-VAL
          GLOBAL_VEL_Y
          GLOBAL_VEL_Z-VAL
          GLOBAL_VEL_Z
          NED_ACC_X-VAL
          NED_ACC_X
          NED_ACC_Y-VAL
          NED_ACC_Y
          NED_ACC_Z-VAL
          NED_ACC_Z
          BODY_ACC_X-VAL
          BODY_ACC_X
          BODY_ACC_Y-VAL
          BODY_ACC_Y
          BODY_ACC_Z-VAL
          BODY_ACC_Z
          REL_POS_XB-VAL
          REL_POS_XB
          REL_POS_YB-VAL
          REL_POS_YB
          REL_POS_ZB-VAL
          REL_POS_ZB
          REL_VEL_XB-VAL
          REL_VEL_XB
          REL_VEL_YB-VAL
          REL_VEL_YB
          REL_VEL_ZB-VAL
          REL_VEL_ZB
          REL_ANGLE_A-VAL
          REL_ANGLE_A
          REL_ANGLE_B-VAL
          REL_ANGLE_B
          REL_ANGLE_C-VAL
          REL_ANGLE_C
          REL_ATT_PITCH-VAL
          REL_ATT_PITCH
          REL_ATT_ROLL-VAL
          REL_ATT_ROLL
          REL_ATT_YAW-VAL
          REL_ATT_YAW
))