(cl:in-package hust_fw_formation_control-msg)
(cl:export '(PLANEID-VAL
          PLANEID
          SP_NED_VEL_X-VAL
          SP_NED_VEL_X
          SP_NED_VEL_Y-VAL
          SP_NED_VEL_Y
          SP_NED_VEL_Z-VAL
          SP_NED_VEL_Z
          SP_LATITUDE-VAL
          SP_LATITUDE
          SP_LONGITUDE-VAL
          SP_LONGITUDE
          SP_ALTITUDE-VAL
          SP_ALTITUDE
          SP_RELATIVE_ALT-VAL
          SP_RELATIVE_ALT
          SP_AIR_SPEED-VAL
          SP_AIR_SPEED
          SP_GROUND_SPEED-VAL
          SP_GROUND_SPEED
          ERR_P_N-VAL
          ERR_P_N
          ERR_P_E-VAL
          ERR_P_E
          ERR_P_D-VAL
          ERR_P_D
          ERR_P_NE-VAL
          ERR_P_NE
          ERR_PXK-VAL
          ERR_PXK
          ERR_PYK-VAL
          ERR_PYK
          ERR_PZK-VAL
          ERR_PZK
          LED_FOL_VXK-VAL
          LED_FOL_VXK
          LED_FOL_VYK-VAL
          LED_FOL_VYK
          LED_FOL_VZK-VAL
          LED_FOL_VZK
          ERR_VXK-VAL
          ERR_VXK
          ERR_VYK-VAL
          ERR_VYK
          ERR_VZK-VAL
          ERR_VZK
          LED_FOL_ETA-VAL
          LED_FOL_ETA
          ETA_DEG-VAL
          ETA_DEG
          ERR_PXB-VAL
          ERR_PXB
          ERR_PYB-VAL
          ERR_PYB
          ERR_PZB-VAL
          ERR_PZB
          ERR_VXB-VAL
          ERR_VXB
          ERR_VYB-VAL
          ERR_VYB
          ERR_VZB-VAL
          ERR_VZB
          LED_FOL_VXB-VAL
          LED_FOL_VXB
          LED_FOL_VYB-VAL
          LED_FOL_VYB
          LED_FOL_VZB-VAL
          LED_FOL_VZB
          A-VAL
          A
          B-VAL
          B
          C-VAL
          C
))