(cl:in-package hust_fw_formation_control-msg)
(cl:export '(PLANEID-VAL
          PLANEID
          TARGET_PLANEID-VAL
          TARGET_PLANEID
          ALTITUDE_LOCK-VAL
          ALTITUDE_LOCK
          IN_AIR-VAL
          IN_AIR
          CONTROL_MODE-VAL
          CONTROL_MODE
          PITCH_ANGLE-VAL
          PITCH_ANGLE
          YAW_ANGLE-VAL
          YAW_ANGLE
          YAW_VALID-VAL
          YAW_VALID
          ROLL_ANGLE-VAL
          ROLL_ANGLE
          ROLL_TRAGET_ANGLE-VAL
          ROLL_TRAGET_ANGLE
          PITCH_TRAGET_ANGLE-VAL
          PITCH_TRAGET_ANGLE
          YAW_TRAGET_ANGLE-VAL
          YAW_TRAGET_ANGLE
          ATT_QUATER-VAL
          ATT_QUATER
          GROUND_SPEED_NED_N-VAL
          GROUND_SPEED_NED_N
          GROUND_SPEED_NED_E-VAL
          GROUND_SPEED_NED_E
          GROUND_SPEED_NED_D-VAL
          GROUND_SPEED_NED_D
          GROUND_SPEED-VAL
          GROUND_SPEED
          GROUND_SPEED_TRAGET-VAL
          GROUND_SPEED_TRAGET
          GLOBAL_VEL_X-VAL
          GLOBAL_VEL_X
          GLOBAL_VEL_Y-VAL
          GLOBAL_VEL_Y
          GLOBAL_VEL_Z-VAL
          GLOBAL_VEL_Z
          AIR_SPEED-VAL
          AIR_SPEED
          WIND_ESTIMATE_X-VAL
          WIND_ESTIMATE_X
          WIND_ESTIMATE_Y-VAL
          WIND_ESTIMATE_Y
          WIND_ESTIMATE_Z-VAL
          WIND_ESTIMATE_Z
          RELATIVE_HIGHT-VAL
          RELATIVE_HIGHT
          RELATIVE_HIGHT_TRAGET-VAL
          RELATIVE_HIGHT_TRAGET
          LATITUDE-VAL
          LATITUDE
          ALTITUDE-VAL
          ALTITUDE
          LONGITUDE-VAL
          LONGITUDE
          RELATIVE_ALT-VAL
          RELATIVE_ALT
          NED_ALTITUDE-VAL
          NED_ALTITUDE
          NED_POS_X-VAL
          NED_POS_X
          NED_POS_Y-VAL
          NED_POS_Y
          NED_POS_Z-VAL
          NED_POS_Z
          NED_VEL_X-VAL
          NED_VEL_X
          NED_VEL_Y-VAL
          NED_VEL_Y
          NED_VEL_Z-VAL
          NED_VEL_Z
          NED_ACC_X-VAL
          NED_ACC_X
          NED_ACC_Y-VAL
          NED_ACC_Y
          NED_ACC_Z-VAL
          NED_ACC_Z
          NED_ACC-VAL
          NED_ACC
          BODY_ACC_X-VAL
          BODY_ACC_X
          BODY_ACC_Y-VAL
          BODY_ACC_Y
          BODY_ACC_Z-VAL
          BODY_ACC_Z
          BODY_ACC-VAL
          BODY_ACC
          BATTERY_VOLTAGE-VAL
          BATTERY_VOLTAGE
          BATTERY_PRECENTAGE-VAL
          BATTERY_PRECENTAGE
          BATTERY_CURRENT-VAL
          BATTERY_CURRENT
))