(cl:in-package hust_fw_formation_control-msg)
(cl:export '(CMD_MODE-VAL
          CMD_MODE
          PITCH_ANGLE_SP-VAL
          PITCH_ANGLE_SP
          YAW_ANGLE_SP-VAL
          YAW_ANGLE_SP
          ROLL_ANGLE_SP-VAL
          ROLL_ANGLE_SP
          THROTTLE_SP-VAL
          THROTTLE_SP
          T_FLIGHT-VAL
          T_FLIGHT
          DATE_PITCH-VAL
          DATE_PITCH
          DATE_PITCHCMD-VAL
          DATE_PITCHCMD
          DATE_ROLL-VAL
          DATE_ROLL
          DATE_ROLLCMD-VAL
          DATE_ROLLCMD
          DATE_V-VAL
          DATE_V
          DATE_VCMD-VAL
          DATE_VCMD
          DATE_H-VAL
          DATE_H
          DATE_HCMD-VAL
          DATE_HCMD
          DATE_VY-VAL
          DATE_VY
          DATE_VYCMD-VAL
          DATE_VYCMD
          DATE_DELTA_PERR-VAL
          DATE_DELTA_PERR
          DATE_DELTA_VERR-VAL
          DATE_DELTA_VERR
          DATE_DELTA_GD-VAL
          DATE_DELTA_GD
          DATE_YAW-VAL
          DATE_YAW
          DATE_YAWCMD-VAL
          DATE_YAWCMD
          DATE_FLAG_ZW-VAL
          DATE_FLAG_ZW
          Z0-VAL
          Z0
          Z1-VAL
          Z1
          Z2-VAL
          Z2
          Z3-VAL
          Z3
          Z4-VAL
          Z4
))